package com.zn.apps.ui_design.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF724C9E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEFDBFF)
val md_theme_light_onPrimaryContainer = Color(0xFF2A0053)
val md_theme_light_secondary = Color(0xFF9C4238)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD5)
val md_theme_light_onSecondaryContainer = Color(0xFF410001)
val md_theme_light_tertiary = Color(0xFF734C9E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEFDBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF2B0052)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1B0261)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1B0261)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_outline = Color(0xFF7B757F)
val md_theme_light_inverseOnSurface = Color(0xFFF4EEFF)
val md_theme_light_inverseSurface = Color(0xFF302175)
val md_theme_light_inversePrimary = Color(0xFFDAB9FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF724C9E)
val md_theme_light_outlineVariant = Color(0xFFCCC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFDAB9FF)
val md_theme_dark_onPrimary = Color(0xFF411A6C)
val md_theme_dark_primaryContainer = Color(0xFF593485)
val md_theme_dark_onPrimaryContainer = Color(0xFFEFDBFF)
val md_theme_dark_secondary = Color(0xFFFFB4AA)
val md_theme_dark_onSecondary = Color(0xFF5F150F)
val md_theme_dark_secondaryContainer = Color(0xFF7D2B23)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_tertiary = Color(0xFFDBB8FF)
val md_theme_dark_onTertiary = Color(0xFF421A6C)
val md_theme_dark_tertiaryContainer = Color(0xFF5A3384)
val md_theme_dark_onTertiaryContainer = Color(0xFFEFDBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B0261)
val md_theme_dark_onBackground = Color(0xFFE5DEFF)
val md_theme_dark_surface = Color(0xFF1B0261)
val md_theme_dark_onSurface = Color(0xFFE5DEFF)
val md_theme_dark_surfaceVariant = Color(0xFF4A454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC4CF)
val md_theme_dark_outline = Color(0xFF958E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1B0261)
val md_theme_dark_inverseSurface = Color(0xFFE5DEFF)
val md_theme_dark_inversePrimary = Color(0xFF724C9E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFDAB9FF)
val md_theme_dark_outlineVariant = Color(0xFF4A454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFD9BBF9)